<aside><div className="surface sticky top-24 rounded-3xl p-6"><div className="flex items-center justify-between"><span className="text-sm font-bold text-[#193c2b] dark:text-white">Service price</span><span className="text-xl font-extrabold text-[#193c2b] dark:text-white">₹{p.price}</span></div><p className="muted mt-1 text-xs">Approximate starting rate</p><div className="mt-6 flex flex-col gap-3"><button onClick={()=>setRequest(true)} className="btn-primary w-full rounded-xl py-3 text-sm font-bold">Request service</button><a href={`tel:${p.name}`} className="pill flex items-center justify-center gap-2 rounded-xl py-3 text-sm font-bold text-[#193c2b] dark:text-white"><Phone size={16}/> Call professional</a></div></div></aside></div>{request && <RequestModal professional={p} onClose={()=>setRequest(false)}/>}</div>; }

function Trust({ icon:I, title, show }: { icon:typeof ShieldCheck; title:string; show:boolean }) { return <div className={`flex items-center gap-2.5 rounded-2xl border p-4 ${show?'border-[#d8eee1] bg-[#f2f8f4] dark:border-[#26382c] dark:bg-[#16221a]':'border-[#dedbd1] opacity-50 dark:border-[#2e3d33]'}`}><I size={18} className={show?'text-[#2e8b62]':'text-[#9aa49b]'}/><span className="text-xs font-bold text-[#193c2b] dark:text-white">{title}</span></div>; }

function RequestModal({ professional:p, onClose }: { professional:Professional; onClose:()=>void }) { const [done,setDone]=useState(false); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="surface w-full max-w-md rounded-3xl p-6 sm:p-8"><div className="flex items-center justify-between"><h2 className="heading text-xl font-bold text-[#193c2b] dark:text-white">Request service</h2><button onClick={onClose}><X size={18}/></button></div>{done?<div><div className="mx-auto my-6 flex h-14 w-14 items-center justify-center rounded-full bg-[#d8eee1] text-[#26714b]"><Check size={28}/></div><h3 className="text-center text-base font-bold text-[#193c2b] dark:text-white">Request sent successfully!</h3><p className="muted mt-2 text-center text-xs">The professional has been notified and will get in touch with you soon.</p><button onClick={onClose} className="btn-primary mt-6 w-full rounded-xl py-3 text-sm font-bold">Done</button></div>:<div className="mt-5 flex flex-col gap-4"><p className="text-xs text-[#657168]">Send a request to <strong>{p.name}</strong> for {p.category.toLowerCase()}.</p><div><label className="mb-1 block text-xs font-bold text-[#657168]">Your name</label><input defaultValue="Demo User" className="w-full rounded-xl border border-[#dedbd1] bg-transparent px-3 py-3 text-sm outline-none"/></div><div><label className="mb-1 block text-xs font-bold text-[#657168]">Phone number</label><input defaultValue="+91 98765 43210" className="w-full rounded-xl border border-[#dedbd1] bg-transparent px-3 py-3 text-sm outline-none"/></div><div><label className="mb-1 block text-xs font-bold text-[#657168]">Describe what you need</label><textarea rows={3} defaultValue="Need help with inspection and repair work." className="w-full rounded-xl border border-[#dedbd1] bg-transparent p-3 text-sm outline-none"/></div><button onClick={()=>setDone(true)} className="btn-primary w-full rounded-xl py-3 text-sm font-bold">Submit request</button></div>}</div></div>; }

function AuthPage({ professional=false, register=false }: { professional?:boolean; register?:boolean }) { const navigate=useNavigate(); return <main className="mx-auto flex min-h-[80vh] max-w-md items-center px-5 py-12"><div className="surface w-full rounded-3xl p-8"><div className="text-center"><span className="flex h-12 w-12 mx-auto items-center justify-center rounded-2xl bg-[#193c2b] text-[#f6bc55]"><Wrench size={24}/></span><h1 className="heading mt-5 text-2xl font-extrabold text-[#193c2b] dark:text-white">{register?(professional?'Join as Professional':'Create your account'):(professional?'Professional Login':'Welcome back')}</h1><p className="muted mt-2 text-xs">{professional?'Manage your local service business with KaamWale.':'Access your saved professionals and requests.'}</p></div><div className="mt-8 flex flex-col gap-4">{register&&<div><label className="mb-1 block text-xs font-bold text-[#657168]">Full name</label><input placeholder="Rahul Sharma" className="w-full rounded-xl border border-[#dedbd1] bg-transparent px-3 py-3 text-sm outline-none"/></div>}<div><label className="mb-1 block text-xs font-bold text-[#657168]">Email address</label><input placeholder="rahul@example.com" className="w-full rounded-xl border border-[#dedbd1] bg-transparent px-3 py-3 text-sm outline-none"/></div><div><label className="mb-1 block text-xs font-bold text-[#657168]">Password</label><input type="password" placeholder="••••••••" className="w-full rounded-xl border border-[#dedbd1] bg-transparent px-3 py-3 text-sm outline-none"/></div><button onClick={()=>navigate(professional?'/professional/dashboard':'/dashboard')} className="btn-primary mt-2 w-full rounded-xl py-3 text-sm font-bold">{register?'Create account':'Log in'}</button></div><div className="mt-6 text-center text-xs">{register?<span>Already have an account? <Link to={professional?'/professional/login':'/login'} className="font-bold text-[#de6b35]">Log in</Link></span>:<span>New to KaamWale? <Link to={professional?'/professional/register':'/register'} className="font-bold text-[#de6b35]">Create account</Link></span>}</div></div></main>; }

function Dashboard({ activeTab, setActiveTab }: { activeTab:string; setActiveTab:(t:string)=>void }) { return <DashboardLayout role="Customer" activeTab={activeTab} setActiveTab={setActiveTab}/>; }
function ProfessionalDashboard({ activeTab, setActiveTab }: { activeTab:string; setActiveTab:(t:string)=>void }) { return <DashboardLayout role="Professional" activeTab={activeTab} setActiveTab={setActiveTab}/>; }
function AdminDashboard({ activeTab, setActiveTab }: { activeTab:string; setActiveTab:(t:string)=>void }) { return <DashboardLayout role="Admin" activeTab={activeTab} setActiveTab={setActiveTab}/>; }

function DashboardLayout({ role, activeTab }: { role:string; activeTab:string; setActiveTab:(t:string)=>void }) { return <main className="mx-auto max-w-[1240px] px-5 py-10 lg:px-8 lg:py-16"><div className="surface rounded-3xl p-6 sm:p-10"><h1 className="heading text-2xl font-extrabold text-[#193c2b] dark:text-white">{role} Dashboard • {activeTab}</h1><p className="muted mt-2 text-sm">This is the {role.toLowerCase()} dashboard workspace for managing your {role==='Admin'?'marketplace operations':role==='Professional'?'services and requests':'activity and bookings'}.</p><div className="mt-8 rounded-2xl border border-dashed border-[#dedbd1] p-10 text-center dark:border-[#35493b]"><p className="text-sm font-bold text-[#193c2b] dark:text-white">Active Section: {activeTab}</p><p className="muted mt-2 text-xs">Fully functional UI views for {activeTab.toLowerCase()} are loaded here.</p></div></div></main>; }

function InfoPage({ title, eyebrow, text }: { title:string; eyebrow:string; text:string }) { return <main className="mx-auto max-w-3xl px-5 py-16 lg:py-24"><span className="text-xs font-bold uppercase tracking-[.18em] text-[#de6b35]">{eyebrow}</span><h1 className="heading mt-3 text-4xl font-extrabold text-[#193c2b] dark:text-white">{title}</h1><p className="muted mt-6 text-base leading-7">{text}</p><p className="muted mt-4 text-base leading-7">KaamWale is committed to building a reliable, human-first ecosystem for everyday services across local communities.</p></main>; }

function Footer({ t }: { t: typeof copy.en }) { return <footer className="border-t border-[#e7e3da] bg-[#f1eee6] dark:border-[#28382e] dark:bg-[#0d1210]"><div className="mx-auto grid max-w-[1240px] gap-10 px-5 py-14 lg:grid-cols-[1.5fr_1fr_1fr_1fr] lg:px-8"><div><Link to="/" className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#193c2b] text-[#f6bc55]"><Wrench size={19}/></span><span className="heading text-xl font-extrabold tracking-tight text-[#193c2b] dark:text-[#e8f2e8]">Kaam<span className="text-[#de6b35]">Wale</span></span></Link><p className="muted mt-4 text-xs leading-6">{t.footerSub}</p><div className="mt-5 flex gap-3 text-[#657168]"><Facebook size={18}/><Linkedin size={18}/><Mail size={18}/></div></div><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#193c2b] dark:text-white">Explore</p><ul className="mt-4 flex flex-col gap-2.5 text-xs text-[#657168] dark:text-[#a8b7aa]"><li><Link to="/categories">Categories</Link></li><li><Link to="/search">Find Professionals</Link></li><li><Link to="/professional/register">Join as Professional</Link></li></ul></div><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#193c2b] dark:text-white">Company</p><ul className="mt-4 flex flex-col gap-2.5 text-xs text-[#657168] dark:text-[#a8b7aa]"><li><Link to="/about">About Us</Link></li><li><Link to="/contact">Contact</Link></li><li><Link to="/privacy">Privacy Policy</Link></li><li><Link to="/terms">Terms of Use</Link></li></ul></div><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#193c2b] dark:text-white">Professional</p><ul className="mt-4 flex flex-col gap-2.5 text-xs text-[#657168] dark:text-white"><li><Link to="/professional/login">Professional Login</Link></li><li><Link to="/professional/register">Register Service</Link></li></ul></div></div><div className="border-t border-[#e7e3da] py-6 text-center text-xs text-[#828e83] dark:border-[#28382e]">© 2026 KaamWale. Local services made simple.</div></footer>; }

function useParamsSafe() { try { return useParams(); } catch { return { id: '1' }; } }

export default App;
