export type Language = 'en' | 'hi' | 'hinglish';
export type Professional = { id: string; name: string; category: string; categorySlug: string; city: string; area: string; rating: number; reviews: number; experience: number; price: number; availability: 'Available today' | 'Busy' | 'Offline'; verified: boolean; about: string; initials: string; color: string };

export const categories = [
  ['Electrician','electrician','Switches, wiring, fans and emergency electrical work.','zap'], ['Plumber','plumber','Leak repairs, fittings and bathroom work.','droplets'], ['House Help','house-help','Reliable help for everyday home tasks.','home'], ['Carpenter','carpenter','Furniture repair and custom fittings.','hammer'], ['Painter','painter','Fresh walls, textures and complete home painting.','paintbrush'], ['Cleaner','cleaner','Deep cleaning for homes, offices and move-outs.','sparkles'], ['AC Technician','ac-technician','AC servicing, installation and repairs.','snowflake'], ['Appliance Repair','appliance-repair','Trusted repairs for everyday appliances.','refrigerator'], ['Mechanic','mechanic','Two-wheeler and car servicing near you.','car-front'], ['Mason','mason','Construction, tiling and renovation work.','hard-hat'], ['Gardener','gardener','Garden care and balcony greens.','leaf'], ['Locksmith','locksmith','Locks, keys and urgent door assistance.','key-round'], ['Pest Control','pest-control','Safe pest treatment for homes and businesses.','bug'], ['Mover & Packer','mover-packer','Careful local shifting and packing support.','package'], ['Computer Repair','computer-repair','Laptop, desktop and network troubleshooting.','laptop'], ['Mobile Repair','mobile-repair','Screen, battery and software repairs.','smartphone']
] as const;

export const professionals: Professional[] = [
  {id:'p1',name:'Rakesh Sharma',category:'Electrician',categorySlug:'electrician',city:'Jaipur',area:'Vaishali Nagar',rating:4.9,reviews:128,experience:12,price:299,availability:'Available today',verified:true,about:'Residential electrical specialist known for neat work and quick response.',initials:'RS',color:'#d97706'},
  {id:'p2',name:'Mohammed Salim',category:'Plumber',categorySlug:'plumber',city:'Jaipur',area:'Mansarovar',rating:4.8,reviews:94,experience:9,price:249,availability:'Available today',verified:true,about:'From urgent leaks to full bathroom fittings, I keep things simple.',initials:'MS',color:'#0f766e'},
  {id:'p3',name:'Meena Devi',category:'House Help',categorySlug:'house-help',city:'Delhi',area:'Saket',rating:4.9,reviews:76,experience:8,price:199,availability:'Available today',verified:true,about:'Careful, dependable household support for busy families.',initials:'MD',color:'#be185d'},
  {id:'p4',name:'Vikram Singh',category:'AC Technician',categorySlug:'ac-technician',city:'Jaipur',area:'Malviya Nagar',rating:4.7,reviews:61,experience:10,price:399,availability:'Busy',verified:true,about:'AC installation and service for all major brands.',initials:'VS',color:'#2563eb'},
  {id:'p5',name:'Amit Verma',category:'Carpenter',categorySlug:'carpenter',city:'Mumbai',area:'Andheri West',rating:4.8,reviews:83,experience:15,price:499,availability:'Available today',verified:true,about:'Custom furniture, modular repairs and precise woodwork.',initials:'AV',color:'#92400e'},
  {id:'p6',name:'Pooja Joshi',category:'Cleaner',categorySlug:'cleaner',city:'Bangalore',area:'Indiranagar',rating:4.9,reviews:112,experience:7,price:349,availability:'Available today',verified:true,about:'Deep cleaning that leaves your home feeling brand new.',initials:'PJ',color:'#7c3aed'},
  {id:'p7',name:'Arjun Patel',category:'Mechanic',categorySlug:'mechanic',city:'Ahmedabad',area:'Navrangpura',rating:4.6,reviews:48,experience:11,price:299,availability:'Available today',verified:false,about:'Two-wheeler diagnostics, servicing and honest advice.',initials:'AP',color:'#374151'},
  {id:'p8',name:'Neeraj Kumar',category:'Computer Repair',categorySlug:'computer-repair',city:'Pune',area:'Kothrud',rating:4.8,reviews:67,experience:6,price:399,availability:'Available today',verified:true,about:'Laptop, desktop and Wi-Fi issues sorted at your doorstep.',initials:'NK',color:'#0369a1'},
  {id:'p9',name:'Farhan Khan',category:'Painter',categorySlug:'painter',city:'Hyderabad',area:'Banjara Hills',rating:4.7,reviews:55,experience:13,price:599,availability:'Offline',verified:true,about:'Interior painting with clean finishes and colour guidance.',initials:'FK',color:'#c2410c'},
  {id:'p10',name:'Suresh Yadav',category:'Locksmith',categorySlug:'locksmith',city:'Delhi',area:'Rohini',rating:4.8,reviews:41,experience:14,price:299,availability:'Available today',verified:true,about:'Fast, reliable lock replacement and emergency opening.',initials:'SY',color:'#475569'}
];

export const copy = {
 en: { nav:['Home','Categories','How it works','For professionals','About'], hero:'Kaam ho koi bhi, KaamWale hai na!', heroSub:'Find trusted electricians, plumbers, cleaners, helpers and other local professionals near you.', search:'Find a professional near you', service:'What service do you need?', location:'Enter your city or area', find:'Find a KaamWala', join:'Join as a Professional', categories:'Popular categories', categoriesSub:'Everyday help, just a tap away.', how:'How KaamWale works', why:'Why choose KaamWale?', featured:'Trusted professionals near you', cta:'Apna hunar, apna kaam, apni pehchaan.', viewAll:'View all categories' },
 hi: { nav:['होम','श्रेणियां','कैसे काम करता है','प्रोफेशनल्स के लिए','हमारे बारे में'], hero:'काम हो कोई भी, KaamWale है ना!', heroSub:'अपने पास भरोसेमंद इलेक्ट्रीशियन, प्लंबर, क्लीनर और अन्य प्रोफेशनल खोजें।', search:'अपने पास प्रोफेशनल खोजें', service:'आपको कौन सी सेवा चाहिए?', location:'शहर या एरिया लिखें', find:'KaamWala खोजें', join:'प्रोफेशनल बनें', categories:'लोकप्रिय सेवाएं', categoriesSub:'हर रोज़ की मदद, बस एक टैप दूर।', how:'KaamWale कैसे काम करता है', why:'KaamWale क्यों चुनें?', featured:'आपके पास भरोसेमंद प्रोफेशनल', cta:'अपना हुनर, अपना काम, अपनी पहचान।', viewAll:'सभी श्रेणियां देखें' },
 hinglish: { nav:['Home','Categories','Kaise kaam karta hai','Professionals ke liye','About'], hero:'Kaam ho koi bhi, KaamWale hai na!', heroSub:'Apne paas trusted electricians, plumbers, cleaners aur local professionals dhoondhein.', search:'Apne paas professional dhoondhein', service:'Kaunsi service chahiye?', location:'City ya area enter karein', find:'KaamWala dhoondhein', join:'Professional banein', categories:'Popular categories', categoriesSub:'Roz ke kaam ki help, bas ek tap door.', how:'KaamWale kaise kaam karta hai', why:'KaamWale kyun choose karein?', featured:'Aapke paas trusted professionals', cta:'Apna hunar, apna kaam, apni pehchaan.', viewAll:'All categories dekhein' }
};
